name: My First Github Actions
on: [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - run: tree
            - uses: actions/checkout@v2
            - run: tree